variables:
  buildConfiguration: 'Debug'

jobs:
- job: BuildAndRunTests
  displayName: Build and run tests
  pool:
    vmImage: windows-latest
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: test
      projects: '**\*.csproj'
      arguments: -c $(buildConfiguration)