variables:
  buildConfiguration: 'Debug'

jobs:
- job: BuildAndRunTests
  displayName: Build and run tests
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: test
      projects: 'AtataSamples.VS2019.sln'
      arguments: -c $(buildConfiguration)